Repository KPC-U16/CHaserRuleGuide-Pub, pull requests merged in 2024-11, with the labels that each got.

#4 対戦ルールのformatを正規化
  rule.md
Labels: documentation, enhancement

#7 mkdocsへ移行
  .gitignore
  docs/index.md
  docs/stylesheets/extra.css
  mkdocs.yml
  requirements.txt
Labels: documentation

#8 mkdocsのbuild環境を整備
  .github/workflows/mkdocs-deploy.yml
  .gitignore
Labels: enhancement

#15 表示崩れを修正、コード規約に対応
  docs/index.md
Labels: bug

#13 再試合する場合としない場合で整理
  docs/index.md
Labels: enhancement
